<?php

namespace Dime\TimetrackerBundle\Entity;

use Dime\TimetrackerBundle\Entity\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * find all activities (in reverted order)
     *
     * @return array
     */
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM DimeTimetrackerBundle:Activity p ORDER BY p.id DESC')
            ->getResult();
    }
}
