<?php

namespace Dime\TimetrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

    /**
     * finds all entities and converts them into arrays
     *
     * @todo move this to EntityRepository ?
     * @return array
     */
    public function allToArray()
    {
        $data = array();
        $activities = $this->findAll();
        foreach ($activities as $activity)
        {
            $data[] = $activity->toArray();
        }

        return $data;
    }
}