<?php

namespace Dime\TimetrackerBundle\Entity;

use Doctrine\ORM\EntityRepository as Base;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends Base
{

    /**
     * finds all entities and converts them into arrays
     *
     * @return array
     */
    public function allToArray()
    {
        $data = array();
        $entities = $this->findAll();
        foreach ($entities as $entity)
        {
            $data[] = $entity->toArray();
        }

        return $data;
    }
}
